export interface Character {
  name: string;
}

export const characterNames: Character[] = [
  { name: "3-D Man" },
  { name: "A-Bomb (HAS)" },
  { name: "A.I.M." },
  { name: "Aaron Stack" },
  { name: "Abomination (Emil Blonsky)" },
  { name: "Abomination (Ultimate)" },
  { name: "Absorbing Man" },
  { name: "Abyss" },
  { name: "Abyss (Age of Apocalypse)" },
  { name: "Adam Destine" },
  { name: "Adam Warlock" },
  { name: "Aegis (Trey Rollins)" },
  { name: "Agent Brand" },
  { name: "Agent X (Nijo)" },
  { name: "Agent Zero" },
  { name: "Agents of Atlas" },
  { name: "Aginar" },
  { name: "Air-Walker (Gabriel Lan)" },
  { name: "Ajak" },
  { name: "Ajaxis" },
  { name: "Akemi" },
  { name: "Alain" },
  { name: "Albert Cleary" },
  { name: "Albion" },
  { name: "Alex Power" },
  { name: "Alex Wilder" },
  { name: "Alexa Mendez" },
  { name: "Alexander Pierce" },
  { name: "Alice" },
  { name: "Alicia Masters" },
  { name: "Alpha Flight" },
  { name: "Alpha Flight (Ultimate)" },
  { name: "Alvin Maker" },
  { name: "Amadeus Cho" },
  { name: "Amanda Sefton" },
  { name: "Amazoness" },
  { name: "American Eagle (Jason Strongbow)" },
  { name: "Amiko" },
  { name: "Amora" },
  { name: "Amphibian (Earth-712)" },
  { name: "Amun" },
  { name: "Ancient One" },
  { name: "Ancient One (Ultimate)" },
  { name: "Angel (Thomas Halloway)" },
  { name: "Angel (Ultimate)" },
  { name: "Angel (Warren Worthington III)" },
  { name: "Angela (Aldrif Odinsdottir)" },
  { name: "Anita Blake" },
  { name: "Anne Marie Hoag" },
  { name: "Annihilus" },
  { name: "Anole" },
  { name: "Ant-Man (Eric O'Grady)" },
  { name: "Ant-Man (Scott Lang)" },
  { name: "Anthem" },
  { name: "Apocalypse" },
  { name: "Apocalypse (Ultimate)" },
  { name: "Aqueduct" },
  { name: "Arachne" },
  { name: "Araña" },
  { name: "Arcade" },
  { name: "Arcana" },
  { name: "Archangel" },
  { name: "Arclight" },
  { name: "Ares" },
  { name: "Argent" },
  { name: "Armadillo" },
  { name: "Armor (Hisako Ichiki)" },
  { name: "Armory" },
  { name: "Arnim Zola" },
  { name: "Arsenic" },
  { name: "Artiee" },
  { name: "Asgardian" },
  { name: "Askew-Tronics" },
  { name: "Asylum" },
  { name: "Atlas (Team)" },
  { name: "Aurora" },
  { name: "Avalanche" },
  { name: "Avengers" },
  { name: "Avengers (Ultimate)" },
  { name: "Azazel (Mutant)" },
  { name: "Banshee" },
  { name: "Banshee (Theresa Rourke)" },
  { name: "Baron Strucker" },
  { name: "Baron Zemo (Heinrich Zemo)" },
  { name: "Baron Zemo (Helmut Zemo)" },
  { name: "Baroness S'Bak" },
  { name: "Barracuda" },
  { name: "Bart Rozum" },
  { name: "Bastion" },
  { name: "Batroc the Leaper" },
  { name: "Battering Ram" },
  { name: "Beak" },
  { name: "Beast" },
  { name: "Beast (Earth-311)" },
  { name: "Beast (Ultimate)" },
  { name: "Becatron" },
  { name: "Bedlam" },
  { name: "Beef" },
  { name: "Beetle (Abner Jenkins)" },
  { name: "Ben Grimm" },
  { name: "Ben Parker" },
  { name: "Ben Reilly" },
  { name: "Ben Urich" },
  { name: "Bengal" },
  { name: "Beta-Ray Bill" },
  { name: "Betty Brant" },
  { name: "Betty Ross" },
  { name: "Beyonder" },
  { name: "Bi-Beast" },
  { name: "Big Bertha" },
  { name: "Big Wheel" },
  { name: "Bill Hollister" },
  { name: "Bishop" },
  { name: "Bishop (Ultimate)" },
  { name: "Black Bird" },
  { name: "Black Bolt" },
  { name: "Black Bolt (Marvel War of Heroes)" },
  { name: "Black Cat" },
  { name: "Black Cat (Ultimate)" },
  { name: "Black Crow" },
  { name: "Black Knight (Sir Percy of Scandia)" },
  { name: "Black Panther" },
  { name: "Black Panther (Ultimate)" },
  { name: "Black Queen" },
  { name: "Black Tarantula" },
  { name: "Black Tom" },
  { name: "Black Widow" },
  { name: "Black Widow (LEGO Marvel Super Heroes)" },
  { name: "Black Widow (Ultimate)" },
  { name: "Black Widow/Natasha Romanoff (MAA)" },
  { name: "Blackheart" },
  { name: "Blacklash" },
  { name: "Blackout" },
  { name: "Blade" },
  { name: "Blastaar" },
  { name: "Blazing Skull" },
  { name: "Blindfold" },
  { name: "Blink" },
  { name: "Blizzard" },
  { name: "Blob" },
  { name: "Blob (Ultimate)" },
  { name: "Blockbuster" },
  { name: "Blok" },
  { name: "Bloke" },
  { name: "Blonde Phantom" },
  { name: "Bloodaxe" },
  { name: "Bloodscream" },
  { name: "Bloodstorm" },
  { name: "Bloodstrike" },
  { name: "Blue Blade" },
  { name: "Blue Marvel" },
  { name: "Blue Shield" },
  { name: "Blur" },
  { name: "Bob, Agent of Hydra" },
  { name: "Boom Boom" },
  { name: "Boomer" },
  { name: "Boomerang" },
  { name: "Box" },
  { name: "Bride of Nine Spiders (Immortal Weapons)" },
  { name: "Bromley" },
  { name: "Brood" },
  { name: "Brother Voodoo" },
  { name: "Brotherhood of Evil Mutants" },
  { name: "Brotherhood of Mutants (Ultimate)" },
  { name: "Bruce Banner" },
  { name: "Brute" },
  { name: "Bucky" },
  { name: "Bug" },
  { name: "Bulldozer" },
  { name: "Bullseye" },
  { name: "Bushwacker" },
  { name: "Butterfly" },
  { name: "Cable" },
  { name: "Cable (Deadpool)" },
  { name: "Cable (Marvel: Avengers Alliance)" },
  { name: "Cable (Ultimate)" },
  { name: "Cable (X-Men: Battle of the Atom)" },
  { name: "Calamity" },
  { name: "Caliban" },
  { name: "Callisto" },
  { name: "Callisto (Age of Apocalypse)" },
  { name: "Calypso" },
  { name: "Cammi" },
  { name: "Cannonball" },
  { name: "Cap'n Oz" },
  { name: "Captain America" },
  { name: "Captain America (House of M)" },
  { name: "Captain America (LEGO Marvel Super Heroes)" },
  { name: "Captain America (Marvel War of Heroes)" },
  { name: "Captain America (Sam Wilson)" },
  { name: "Captain America (Ultimate)" },
  { name: "Captain America/Steve Rogers (MAA)" },
  { name: "Captain Britain" },
  { name: "Captain Britain (Ultimate)" },
  { name: "Captain Cross" },
  { name: "Captain Flint" },
  { name: "Captain Marvel (Carol Danvers)" },
  { name: "Captain Marvel (Genis-Vell)" },
  { name: "Captain Marvel (Mar-Vell)" },
  { name: "Captain Marvel (Monica Rambeau)" },
  { name: "Captain Marvel (Phyla-Vell)" },
  { name: "Captain Midlands" },
  { name: "Captain Stacy" },
  { name: "Captain Universe" },
  { name: "Cardiac" },
  { name: "Caretaker" },
  { name: "Cargill" },
  { name: "Carlie Cooper" },
  { name: "Carmella Unuscione" },
  { name: "Carnage" },
  { name: "Carnage (Ultimate)" },
  { name: "Carol Danvers" },
  { name: "Carol Hines" },
  { name: "Cassandra Nova" },
  { name: "Catseye" },
  { name: "Cecilia Reyes" },
  { name: "Celestials" },
  { name: "Centennial" },
  { name: "Centurions" },
  { name: "Cerebro" },
  { name: "Cerise" },
  { name: "Ch'od" },
  { name: "Chamber" },
  { name: "Chameleon" },
  { name: "Champions" },
  { name: "Changeling" },
  { name: "Charles Xavier" },
  { name: "Charlie Campion" },
  { name: "Chase Stein" },
  { name: "Chat" },
  { name: "Chimera" },
  { name: "Chores MacGillicudy" },
  { name: "Christian Walker" },
  { name: "Chronomancer" },
  { name: "ClanDestine" },
  { name: "Clea" },
  { name: "Clea (Ultimate)" },
  { name: "Clint Barton" },
  { name: "Cloak" },
  { name: "Cloud 9" },
  { name: "Cobalt Man" },
  { name: "Colleen Wing" },
  { name: "Colonel America" },
  { name: "Colossus" },
  { name: "Colossus (Ultimate)" },
  { name: "Confederates of the Curious" },
  { name: "Constrictor" },
  { name: "Contessa (Vera Vidal)" },
  { name: "Controller" },
  { name: "Cornelius" },
  { name: "Corsair" },
  { name: "Cosmo (dog)" },
  { name: "Cottonmouth" },
  { name: "Count Nefaria" },
  { name: "Countess" },
  { name: "Crimson Crusader" },
  { name: "Crimson Dynamo" },
  { name: "Crimson Dynamo (Iron Man 3 - The Official Game)" },
  { name: "Crimson King" },
  { name: "Crossbones" },
  { name: "Crule" },
  { name: "Crusher Hogan" },
  { name: "Crusher Hogan (Ultimate)" },
  { name: "Crystal" },
  { name: "Cuckoo" },
  { name: "Curt Conners" },
  { name: "Cuthbert" },
  { name: "Cyber" },
  { name: "Cyclops" },
  { name: "Cyclops (Ultimate)" },
  { name: "Cyclops (X-Men: Battle of the Atom)" },
  { name: "Cypher" },
  { name: "D'Ken Neramani" },
  { name: "Dagger" },
  { name: "Daily Bugle" },
  { name: "Daimon Hellstrom" },
  { name: "Daken" },
  { name: "Dakota North" },
  { name: "Damage Control" },
  { name: "Dani Moonstar" },
  { name: "Danny Rand" },
  { name: "Daredevil" },
  { name: "Daredevil (LEGO Marvel Super Heroes)" },
  { name: "Daredevil (Marvel Heroes)" },
  { name: "Daredevil (Ultimate)" },
  { name: "Dargo Ktor" },
  { name: "Dark Avengers" },
  { name: "Dark Beast" },
  { name: "Dark Phoenix" },
  { name: "Dark X-Men" },
  { name: "Darkhawk" },
  { name: "Darkstar" },
  { name: "Darwin" },
  { name: "Dazzler" },
  { name: "Dazzler (Ultimate)" },
  { name: "Deacon Frost" },
  { name: "Dead Girl" },
  { name: "Deadpool" },
  { name: "Deadpool (Deadpool)" },
  { name: "Deadpool (LEGO Marvel Super Heroes)" },
  { name: "Deadpool (X-Men: Battle of the Atom)" },
  { name: "Death" },
  { name: "Deathbird" },
  { name: "Deathcry" },
  { name: "Deathlok" },
  { name: "Deathstrike (Ultimate)" },
  { name: "Debra Whitman" },
  { name: "Debrii" },
  { name: "Deena Pilgrim" },
  { name: "Defenders" },
  { name: "Demogoblin" },
  { name: "Destiny" },
  { name: "Detective Soap" },
  { name: "Deviants" },
  { name: "Devil Dinosaur (Devil Dinosaur)" },
  { name: "Devil Dinosaur (HAS)" },
  { name: "Devos" },
  { name: "Dexter Bennett" },
  { name: "Diablo" },
  { name: "Diamondback (Rachel Leighton)" },
  { name: "Dinah Soar" },
  { name: "Dirk Anger" },
  { name: "Doc Samson" },
  { name: "Doctor Doom" },
  { name: "Doctor Doom (Ultimate)" },
  { name: "Doctor Faustus" },
  { name: "Doctor Octopus" },
  { name: "Doctor Octopus (Ultimate)" },
  { name: "Doctor Spectrum" },
  { name: "Doctor Strange" },
  { name: "Doctor Strange (Ultimate)" },
  { name: "Dog Brother #1" },
  { name: "Domino" },
  { name: "Donald Blake" },
  { name: "Doomsday Man" },
  { name: "Doop" },
  { name: "Doorman" },
  { name: "Dorian Gray" },
  { name: "Dormammu" },
  { name: "Dormammu (Ultimate)" },
  { name: "Dr. Strange (Marvel: Avengers Alliance)" },
  { name: "Dracula" },
  { name: "Dragon Lord" },
  { name: "Dragon Man" },
  { name: "Drax" },
  { name: "Dreadnoughts" },
  { name: "Dreaming Celestial" },
  { name: "Druig" },
  { name: "Dum Dum Dugan" },
  { name: "Dust" },
  { name: "Earthquake" },
  { name: "Echo" },
  { name: "Eddie Brock" },
  { name: "Eddie Lau" },
  { name: 'Edward "Ted" Forrester' },
  { name: "Edwin Jarvis" },
  { name: "Ego" },
  { name: "Electro" },
  { name: "Electro (Ultimate)" },
  { name: "Elektra" },
  { name: "Elektra (Ultimate)" },
  { name: "Elements of Doom" },
  { name: "Elite" },
  { name: "Elixir" },
  { name: "Elloe Kaifi" },
  { name: "Elsa Bloodstone" },
  { name: "Emma Frost" },
  { name: "Empath" },
  { name: "Emplate" },
  { name: "Enchantress (Amora)" },
  { name: "Enchantress (Sylvie Lushton)" },
  { name: "Ender Wiggin" },
  { name: "Energizer" },
  { name: "Epoch" },
  { name: "Erik the Red" },
  { name: "Eternals" },
  { name: "Eternity" },
  { name: "Excalibur" },
  { name: "Exiles" },
  { name: "Exodus" },
  { name: "Expediter" },
  { name: "Ezekiel" },
  { name: "Ezekiel Stane" },
  { name: "Fabian Cortez" },
  { name: "Falcon" },
  { name: "Falcon/Sam Wilson (MAA)" },
  { name: "Fallen One" },
  { name: "Famine" },
  { name: "Fantastic Four" },
  { name: "Fantastic Four (Ultimate)" },
  { name: "Fantastick Four" },
  { name: "Fantomex" },
  { name: "Fat Cobra" },
  { name: "Felicia Hardy" },
  { name: "Fenris" },
  { name: "Feral" },
  { name: "Fin Fang Foom" },
  { name: "Firebird" },
  { name: "Firebrand" },
  { name: "Firedrake" },
  { name: "Firelord" },
  { name: "Firestar" },
  { name: "Firestar (Ultimate)" },
  { name: "Fixer (Paul Norbert Ebersol)" },
  { name: "Flatman" },
  { name: "Flying Dutchman" },
  { name: "Foggy Nelson" },
  { name: "Force Works" },
  { name: "Forearm" },
  { name: "Forge" },
  { name: "Forge (Ultimate)" },
  { name: "Forgotten One" },
  { name: "Frank Castle" },
  { name: "Frankenstein's Monster" },
  { name: "Franklin Richards" },
  { name: "Franklin Storm" },
  { name: "Freak" },
  { name: "Frightful Four" },
  { name: "Frog Thor" },
  { name: "Frog-Man" },
  { name: "Gabe Jones" },
  { name: "Galactus" },
  { name: "Galia" },
  { name: "Gambit" },
  { name: "Gamma Corps" },
  { name: "Gamora" },
  { name: "Gamora (Marvel War of Heroes)" },
  { name: "Gargoyle" },
  { name: "Gargoyle (Yuri Topolov)" },
  { name: "Garia" },
  { name: "Garrison Kane" },
  { name: "Gateway" },
  { name: "Gauntlet (Joseph Green)" },
  { name: "Geiger" },
  { name: "Gene Sailors" },
  { name: "Generation X" },
  { name: "Genesis" },
  { name: "Genis-Vell" },
  { name: "George Stacy (Ultimate)" },
  { name: "Gertrude Yorkes" },
  { name: "Ghost Rider (Daniel Ketch)" },
  { name: "Ghost Rider (Johnny Blaze)" },
  { name: "Ghost Rider (Marvel War of Heroes)" },
  { name: "Giant Girl" },
  { name: "Giant Man" },
  { name: "Giant-dok" },
  { name: "Giant-Man (Ultimate)" },
  { name: "Gideon" },
  { name: "Git Hoskins" },
  { name: "Gladiator (Kallark)" },
  { name: "Gladiator (Melvin Potter)" },
  { name: "Glenn Talbot" },
  { name: "Glorian" },
  { name: "Goblin Queen" },
  { name: "Golden Guardian" },
  { name: "Goliath (Bill Foster)" },
  { name: "Gorgon" },
  { name: "Gorilla Man" },
  { name: "Grandmaster" },
  { name: "Gravity" },
  { name: "Great Lakes Avengers" },
  { name: "Green Goblin (Barry Norman Osborn)" },
  { name: "Green Goblin (Harry Osborn)" },
  { name: "Green Goblin (Ultimate)" },
  { name: "Gressill" },
  { name: "Grey Gargoyle" },
  { name: "Greymalkin" },
  { name: "Grim Reaper" },
  { name: "Groot" },
  { name: "Guardian" },
  { name: "Guardians of the Galaxy" },
  { name: "Guardsmen" },
  { name: "Gunslinger" },
  { name: "GW Bridge" },
  { name: "Gwen Stacy" },
  { name: "Gwen Stacy (Ultimate)" },
  { name: "H.A.M.M.E.R." },
  { name: "H.E.R.B.I.E." },
  { name: "Hairball" },
  { name: "Half-Life (Tony Masterson)" },
  { name: "Hammerhead" },
  { name: "Hammerhead (Ultimate)" },
  { name: "Hank Pym" },
  { name: "Hannibal King" },
  { name: "Happy Hogan" },
  { name: "Hardball" },
  { name: "Harley Davidson Cooper" },
  { name: "Harpoon" },
  { name: "Harrier" },
  { name: "Harry Heck" },
  { name: "Harry Osborn" },
  { name: "Harry Osborn (Ultimate)" },
  { name: "Hate-Monger (Adolf Hitler)" },
  { name: "Havok" },
  { name: "Hawkeye" },
  { name: "Hawkeye (Kate Bishop)" },
  { name: "Hawkeye (Marvel Heroes)" },
  { name: "Hawkeye (Ultimate)" },
  { name: "Hawkeye/Clint Barton (MAA)" },
  { name: "Hedge Knight" },
  { name: "Hellcat (Patsy Walker)" },
  { name: "Hellfire Club" },
  { name: "Hellfire Club (Ultimate)" },
  { name: "Hellion" },
  { name: "Hellions (Squad)" },
  { name: "Hemingway" },
  { name: "Henry Peter Gyrich" },
  { name: "Hepzibah" },
  { name: "Hercules" },
  { name: "Heroes For Hire" },
  { name: "Hex" },
  { name: "High Evolutionary" },
  { name: "Hindsight Lad" },
  { name: "Hiroim" },
  { name: "Hitman" },
  { name: "Hitomi Sakuma" },
  { name: "Hobgoblin (Jason Macendale)" },
  { name: "Hobgoblin (Robin Borne)" },
  { name: "Hobgoblin (Roderick Kingsley)" },
  { name: "Holocaust (Age of Apocalypse)" },
  { name: "Holy" },
  { name: "Hope Summers" },
  { name: "Howard Saint" },
  { name: "Howard The Duck" },
  { name: "Hulk" },
  { name: "Hulk (HAS)" },
  { name: "Hulk (LEGO Marvel Super Heroes)" },
  { name: "Hulk (Marvel Zombies)" },
  { name: "Hulk (Marvel: Avengers Alliance)" },
  { name: "Hulk (Ultimate)" },
  { name: "Hulk-dok" },
  { name: "Hulk/Bruce Banner (MAA)" },
  { name: "Hulkling" },
  { name: "Human Cannonball" },
  { name: "Human Fly (Richard Deacon)" },
  { name: "Human Robot" },
  { name: "Human Torch" },
  { name: "Human Torch (Jim Hammond)" },
  { name: "Human Torch (Ultimate)" },
  { name: "Humbug" },
  { name: "Husk" },
  { name: "Hussar" },
  { name: "Hydra" },
  { name: "Hydro-Man" },
  { name: "Hyperion (Earth-712)" },
  { name: "Hypno-Hustler" },
  { name: "Iceman" },
  { name: "Iceman (Ultimate)" },
  { name: "Iceman (X-Men: Battle of the Atom)" },
  { name: "Ikaris" },
  { name: "Illuminati" },
  { name: "Ilyana Rasputin" },
  { name: "Imp" },
  { name: "Imperfects" },
  { name: "Imperial Guard" },
  { name: "Impossible Man" },
  { name: "In-Betweener" },
  { name: "Inertia" },
  { name: "Infant Terrible" },
  { name: "Inhumans" },
  { name: "Ink" },
  { name: "Invaders" },
  { name: "Invisible Woman" },
  { name: "Invisible Woman (Marvel: Avengers Alliance)" },
  { name: "Invisible Woman (Ultimate)" },
  { name: "Iron Cross Army" },
  { name: "Iron Fist (Bei Bang-Wen)" },
  { name: "Iron Fist (Danny Rand)" },
  { name: "Iron Fist (Orson Randall)" },
  { name: "Iron Fist (Quan Yaozu)" },
  { name: "Iron Fist (USM)" },
  { name: "Iron Fist (Wu Ao-Shi)" },
  { name: "Iron Lad" },
  { name: "Iron Man" },
  { name: "Iron Man (Iron Man 3 - The Official Game)" },
  { name: "Iron Man (LEGO Marvel Super Heroes)" },
  { name: "Iron Man (Marvel Heroes)" },
  { name: "Iron Man (Marvel War of Heroes)" },
  { name: "Iron Man (Ultimate)" },
  { name: "Iron Man/Tony Stark (MAA)" },
  { name: "Iron Monger" },
  { name: "Iron Patriot" },
  { name: "Iron Patriot (James Rhodes)" },
  { name: "Ironclad" },
  { name: "J. Jonah Jameson" },
  { name: "Jack Flag" },
  { name: "Jack Murdock" },
  { name: "Jack O' Lantern" },
  { name: "Jack Power" },
  { name: "Jackal" },
  { name: "Jackpot" },
  { name: "James Buchanan Barnes" },
  { name: "James Howlett" },
  { name: "Jamie Braddock" },
  { name: "Jane Foster" },
  { name: "Janus, the Nega-Man" },
  { name: "Jasper Sitwell" },
  { name: "Jazinda" },
  { name: "Jean Grey" },
  { name: "Jean Grey (Ultimate)" },
  { name: "Jennifer Smith" },
  { name: "Jeryn Hogarth" },
  { name: "Jessica Drew" },
  { name: "Jessica Jones" },
  { name: "Jetstream" },
  { name: "Jigsaw" },
  { name: "Jimmy Woo" },
  { name: "Joan the Mouse" },
  { name: "Jocasta" },
  { name: "John Farson" },
  { name: "John Jameson" },
  { name: "John Porter" },
  { name: "John Wraith" },
  { name: "Johnny Blaze" },
  { name: "Johnny Storm" },
  { name: "Joseph" },
  { name: "Joshua Kane" },
  { name: "Josiah X" },
  { name: "Joystick" },
  { name: "Jubilee" },
  { name: "Jubilee (Age of Apocalypse)" },
  { name: "Juggernaut" },
  { name: "Jule Carpenter" },
  { name: "Julian Keller" },
  { name: "Junta" },
  { name: "Justice" },
  { name: "Justin Hammer" },
  { name: "Ka-Zar" },
  { name: "Kabuki" },
  { name: "Kang" },
  { name: "Karen O'Malley" },
  { name: "Karen Page" },
  { name: "Karma" },
  { name: "Karnak" },
  { name: "Karolina Dean" },
  { name: "Kat Farrell" },
  { name: "Kate Bishop" },
  { name: "Katie Power" },
  { name: "Ken Ellis" },
  { name: "Khan" },
  { name: "Kid Colt" },
  { name: "Killer Shrike" },
  { name: "Killmonger" },
  { name: "Killraven" },
  { name: "King Bedlam" },
  { name: "King Cobra" },
  { name: "Kingpin" },
  { name: "Kinsey Walden" },
  { name: "Kitty Pryde" },
  { name: "Kitty Pryde (X-Men: Battle of the Atom)" },
  { name: "Klaw" },
  { name: "Komodo (Melati Kusuma)" },
  { name: "Korath" },
  { name: "Korg" },
  { name: "Korvac" },
  { name: "Kraven the Hunter" },
  { name: "Kree" },
  { name: "Krista Starr" },
  { name: "Kronos" },
  { name: "Kulan Gath" },
  { name: "Kylun" },
  { name: "La Nuit" },
  { name: "Lady Bullseye" },
  { name: "Lady Deathstrike" },
  { name: "Lady Mastermind" },
  { name: "Lady Ursula" },
  { name: "Lady Vermin" },
  { name: "Lake" },
  { name: "Landau" },
  { name: "Lava-Man" },
  { name: "Layla Miller" },
  { name: "Leader" },
  { name: "Leech" },
  { name: "Legion" },
  { name: "Lei Kung, The Thunderer" },
  { name: "Lenny Balinger" },
  { name: "Leo (Zodiac)" },
  { name: "Leopardon" },
  { name: "Leper Queen" },
  { name: "Lester" },
  { name: "Lethal Legion" },
  { name: "Lieutenant Marcus Stone" },
  { name: "Lifeguard" },
  { name: "Lightning Lords of Nepal" },
  { name: "Lightspeed" },
  { name: "Lila Cheney" },
  { name: "Lilandra" },
  { name: "Lilith" },
  { name: "Lily Hollister" },
  { name: "Lionheart" },
  { name: "Living Lightning" },
  { name: "Living Mummy" },
  { name: "Living Tribunal" },
  { name: "Liz Osborn" },
  { name: "Lizard" },
  { name: "Lizard (Ultimate)" },
  { name: "Loa" },
  { name: "Lockheed" },
  { name: "Lockjaw" },
  { name: "Logan" },
  { name: "Loki" },
  { name: "Loki (LEGO Marvel Super Heroes)" },
  { name: "Loners" },
  { name: "Longshot" },
  { name: "Longshot (Ultimate)" },
  { name: "Lord Hawal" },
  { name: "Lord Tyger" },
  { name: "Lords of Avalon" },
  { name: "Lorna Dane" },
  { name: "Luckman" },
  { name: "Lucky Pierre" },
  { name: "Lucy in the Sky" },
  { name: "Luke Cage" },
  { name: "Luminals" },
  { name: "Lyja" },
  { name: "M (Monet St. Croix)" },
  { name: "M.O.D.A.M." },
  { name: "M.O.D.O.G." },
  { name: "M.O.D.O.K." },
  { name: "M.O.D.O.K. (Iron Man 3 - The Official Game)" },
  { name: "Ma Gnuci" },
  { name: "Mac Gargan" },
  { name: "Mach IV" },
  { name: "Machine Man" },
  { name: "Mad Thinker" },
  { name: "Madame Hydra" },
  { name: "Madame Masque" },
  { name: "Madame Web (Julia Carpenter)" },
  { name: "Maddog" },
  { name: "Madelyne Pryor" },
  { name: "Madripoor" },
  { name: "Madrox" },
  { name: "Maelstrom" },
  { name: "Maestro" },
  { name: "Magdalene" },
  { name: "Maggott" },
  { name: "Magik (Amanda Sefton)" },
  { name: "Magik (Illyana Rasputin)" },
  { name: "Maginty" },
  { name: "Magma (Amara Aquilla)" },
  { name: "Magneto" },
  { name: "Magneto (Age of Apocalypse)" },
  { name: "Magneto (House of M)" },
  { name: "Magneto (Ultimate)" },
  { name: "Magneto (X-Men: Battle of the Atom)" },
  { name: "Magus (Adam Warlock)" },
  { name: "Magus (Technarch)" },
  { name: "Major Mapleleaf" },
  { name: "Makkari" },
  { name: "Malcolm Colcord" },
  { name: "Malice (Earth-161)" },
  { name: "Man-Thing" },
  { name: "Man-Wolf" },
  { name: "Mandarin" },
  { name: "Mandrill" },
  { name: "Mandroid" },
  { name: "Manta" },
  { name: "Mantis" },
  { name: "Marauders" },
  { name: "Marcus Van Sciver" },
  { name: "Maria Hill" },
  { name: "Mariko Yashida" },
  { name: "Marrow" },
  { name: "Marten Broadcloak" },
  { name: "Martin Li" },
  { name: "Marvel Apes" },
  { name: "Marvel Boy" },
  { name: "Marvel Zombies" },
  { name: "Marvex" },
  { name: "Mary Jane Watson" },
  { name: "Mary Jane Watson (House of M)" },
  { name: "Mary Jane Watson (Ultimate)" },
  { name: "Masked Marvel (Unrevealed)" },
  { name: "Masque" },
  { name: "Master Chief" },
  { name: "Master Mold" },
  { name: "Mastermind" },
  { name: "Masters of Evil" },
  { name: "Mathemanic" },
  { name: "Matsu'o Tsurayaba" },
  { name: "Matthew Murdock" },
  { name: "Mattie Franklin" },
  { name: "Mauler" },
  { name: "Maverick (Chris Bradley)" },
  { name: "Maverick (Christoph Nord)" },
  { name: "Maximus" },
  { name: "May Parker" },
  { name: "Medusa" },
  { name: "Meggan" },
  { name: "Meltdown" },
  { name: "Menace" },
  { name: "Mentallo" },
  { name: "Mentor" },
  { name: "Mephisto" },
  { name: "Mephistopheles" },
  { name: "Mercury" },
  { name: "Mesmero" },
  { name: "Metal Master" },
  { name: "Meteorite" },
  { name: "MI: 13" },
  { name: "Micro/Macro" },
  { name: "Microbe" },
  { name: "Microchip" },
  { name: "Micromax" },
  { name: "Midnight (Earth-811)" },
  { name: "Miek" },
  { name: "Mikhail Rasputin" },
  { name: "Millenium Guard" },
  { name: "Millie the Model" },
  { name: "Mimic" },
  { name: "Mindworm" },
  { name: "Miracleman" },
  { name: "Miss America" },
  { name: "Mister Fear" },
  { name: "Mister Sinister" },
  { name: "Mister Sinister (Deadpool)" },
  { name: "Mister Sinister (House of M)" },
  { name: "Mister Sinister (Ultimate)" },
  { name: "Misty Knight" },
  { name: "Mockingbird" },
  { name: "Moira MacTaggert" },
  { name: "Moira MacTaggert (Ultimate)" },
  { name: "Mojo" },
  { name: "Mole Man" },
  { name: "Molecule Man" },
  { name: "Molly Hayes" },
  { name: "Molly Von Richtofen" },
  { name: "Molten Man" },
  { name: "Mongoose" },
  { name: "Mongu (Unrevealed)" },
  { name: "Monster Badoon" },
  { name: "Moon Knight" },
  { name: "Moon Knight (House of M)" },
  { name: "Moon Knight (Ultimate)" },
  { name: "Moondragon" },
  { name: "Moonstone" },
  { name: "Morbius" },
  { name: "Mordo" },
  { name: "Morg" },
  { name: "Morgan Stark" },
  { name: "Morlocks" },
  { name: "Morlun" },
  { name: "Morph" },
  { name: "Mother Askani" },
  { name: "Mr. Bumpo" },
  { name: "Mr. Fantastic" },
  { name: "Mr. Fantastic (Ultimate)" },
  { name: "Mr. Fish" },
  { name: "Mr. Fixit" },
  { name: "Mr. Hyde" },
  { name: "Mr. Immortal" },
  { name: "Mr. Meugniot" },
  { name: "Mr. Negative" },
  { name: "Mr. Payback" },
  { name: "Mr. X" },
  { name: "Ms. Marvel (Kamala Khan)" },
  { name: "MS2" },
  { name: "Mulholland Black" },
  { name: "Multiple Man" },
  { name: "MVP" },
  { name: "Mysterio" },
  { name: "Mysterio (Daniel Berkhart)" },
  { name: "Mysterio (Francis Klum)" },
  { name: "Mystique" },
  { name: "Mystique (Age of Apocalypse)" },
  { name: "Mystique (House of M)" },
  { name: "Mystique (Ultimate)" },
  { name: "Nakia (Nakia)" },
  { name: "Namor" },
  { name: "Namora" },
  { name: "Namorita" },
  { name: "Naoko" },
  { name: "Natasha Romanoff" },
  { name: "Nebula" },
  { name: "Nehzno" },
  { name: "Nekra" },
  { name: "Nemesis" },
  { name: "Network" },
  { name: "New Goblin" },
  { name: "New Mutants" },
  { name: "New Warriors" },
  { name: "New X-Men" },
  { name: "Newton Destine" },
  { name: "Next Avengers" },
  { name: "Nextwave" },
  { name: "Nick Fury" },
  { name: "Nick Fury (LEGO Marvel Super Heroes)" },
  { name: "Nick Fury (Ultimate)" },
  { name: "Nico Minoru" },
  { name: "Nicolaos" },
  { name: "Night Nurse (Earth-9997)" },
  { name: "Night Thrasher" },
  { name: "Night Thrasher (Dwayne Taylor)" },
  { name: "Nightcrawler" },
  { name: "Nightcrawler (Ultimate)" },
  { name: "Nighthawk" },
  { name: "Nightmare" },
  { name: "Nightshade" },
  { name: "Nine-Fold Daughters of Xao" },
  { name: "Nitro" },
  { name: "Nocturne" },
  { name: "Nomad" },
  { name: "Nomad (Rikki Barnes)" },
  { name: "Nomad (Steve Rogers)" },
  { name: "Norman Osborn" },
  { name: "Norrin Radd" },
  { name: "Northstar" },
  { name: "Nova" },
  { name: "Nova (Frankie Raye)" },
  { name: "Nova (Sam Alexander)" },
  { name: "Nova (USM)" },
  { name: "Nuke" },
  { name: "Obadiah Stane" },
  { name: "Odin" },
  { name: "Ogun" },
  { name: "Okoye" },
  { name: "Old Lace" },
  { name: "Omega Flight" },
  { name: "Omega Red" },
  { name: "Omega Sentinel" },
  { name: "Omega the Unknown" },
  { name: "Onslaught" },
  { name: "Onslaught (Ultimate)" },
  { name: "Oracle" },
  { name: "Ord" },
  { name: "Orphan" },
  { name: "Orphan-Maker" },
  { name: "Otto Octavius" },
  { name: "Outlaw Kid" },
  { name: "Overlord" },
  { name: "Owl" },
  { name: "Ozymandias" },
  { name: "Paibok" },
  { name: "Paladin" },
  { name: "Pandemic" },
  { name: "Paper Doll" },
  { name: "Patch" },
  { name: "Patriot" },
  { name: "Payback" },
  { name: "Penance (Robert Baldwin)" },
  { name: "Pepper Potts" },
  { name: "Pestilence" },
  { name: "Pet Avengers" },
  { name: "Pete Wisdom" },
  { name: "Peter Parker" },
  { name: "Peter Quill" },
  { name: "Phalanx" },
  { name: "Phantom Reporter" },
  { name: "Phil Coulson (Phil Coulson)" },
  { name: "Phil Sheldon" },
  { name: "Photon" },
  { name: "Phyla-Vell" },
  { name: "Piledriver" },
  { name: "Pip" },
  { name: "Pixie" },
  { name: "Plazm" },
  { name: "Polaris" },
  { name: "Post" },
  { name: "Power Man (USM)" },
  { name: "Power Pack" },
  { name: "Praxagora" },
  { name: "Preak" },
  { name: "Pretty Boy" },
  { name: "Pride" },
  { name: "Prima" },
  { name: "Prince of Orphans" },
  { name: "Princess Powerful" },
  { name: "Prism" },
  { name: "Prodigy" },
  { name: "Proemial Gods" },
  { name: "Professor Monster" },
  { name: "Professor X" },
  { name: "Professor X (Ultimate)" },
  { name: "Proteus" },
  { name: "Proteus (House of M)" },
  { name: "Proteus (Ultimate)" },
  { name: "Proudstar" },
  { name: "Prowler" },
  { name: "Prowler (Rick Lawson)" },
  { name: "Psycho-Man" },
  { name: "Psylocke" },
  { name: "PsyNapse" },
  { name: "Puck" },
  { name: "Puck (Zuzha Yu)" },
  { name: "Puff Adder" },
  { name: "pug" },
  { name: "Puma" },
  { name: "Punisher" },
  { name: "Punisher (2099)" },
  { name: "Punisher (Marvel: Avengers Alliance)" },
  { name: "Puppet Master" },
  { name: "Purifiers" },
  { name: "Purple Man" },
  { name: "Pyro" },
  { name: "Quake (Daisy Johnson)" },
  { name: "Quasar (Phyla-Vell)" },
  { name: "Quasar (Wendell Vaughn)" },
  { name: "Quasimodo" },
  { name: "Queen Noir" },
  { name: "Quentin Quire" },
  { name: "Quicksilver" },
  { name: "Quicksilver (Age of Apocalypse)" },
  { name: "Quicksilver (Ultimate)" },
  { name: "Rachel Grey" },
  { name: "Radioactive Man" },
  { name: "Rafael Vega" },
  { name: "Rage" },
  { name: "Raider" },
  { name: "Randall" },
  { name: "Randall Flagg" },
  { name: "Random" },
  { name: "Rattler" },
  { name: "Ravenous" },
  { name: "Rawhide Kid" },
  { name: "Raza" },
  { name: "Reaper" },
  { name: "Reavers" },
  { name: "Reavers (Ultimate)" },
  { name: "Red 9" },
  { name: "Red Ghost" },
  { name: "Red Ghost (Ultimate)" },
  { name: "Red Hulk" },
  { name: "Red Hulk (HAS)" },
  { name: "Red She-Hulk" },
  { name: "Red Shift" },
  { name: "Red Skull" },
  { name: "Red Skull (Albert Malik)" },
  { name: "Red Wolf" },
  { name: "Redwing" },
  { name: "Reptil" },
  { name: "Retro Girl" },
  { name: "Revanche" },
  { name: "Rhino" },
  { name: "Rhodey" },
  { name: "Richard Fisk" },
  { name: "Rick Jones" },
  { name: "Rick Jones (Ultimate)" },
  { name: "Ricochet" },
  { name: "Rictor" },
  { name: "Riptide" },
  { name: "Risque" },
  { name: "Robbie Robertson" },
  { name: "Robert Baldwin" },
  { name: "Robin Chapel" },
  { name: "Rocket Raccoon" },
  { name: "Rocket Raccoon (Marvel Heroes)" },
  { name: "Rocket Racer" },
  { name: "Rockslide" },
  { name: "Rogue" },
  { name: "Rogue (Age of Apocalypse)" },
  { name: "Rogue (Deadpool)" },
  { name: "Rogue (Ultimate)" },
  { name: "Rogue (X-Men: Battle of the Atom)" },
  { name: "Roland Deschain" },
  { name: "Romulus" },
  { name: "Ronan" },
  { name: "Roughhouse" },
  { name: "Roulette" },
  { name: "Roxanne Simpson" },
  { name: "Rumiko Fujikawa" },
  { name: "Runaways" },
  { name: "Russian" },
  { name: "S.H.I.E.L.D." },
  { name: "Sabra" },
  { name: "Sabretooth" },
  { name: "Sabretooth (Age of Apocalypse)" },
  { name: "Sabretooth (House of M)" },
  { name: "Sabretooth (Ultimate)" },
  { name: "Sage" },
  { name: "Salem's Seven (Ultimate)" },
  { name: "Sally Floyd" },
  { name: "Salo" },
  { name: "Sandman" },
  { name: "Santa Claus" },
  { name: "Saracen (Muzzafar Lambert)" },
  { name: "Sasquatch (Walter Langkowski)" },
  { name: "Satana" },
  { name: "Sauron" },
  { name: "Scalphunter" },
  { name: "Scarecrow (Ebenezer Laughton)" },
  { name: "Scarlet Spider (Ben Reilly)" },
  { name: "Scarlet Spider (Kaine)" },
  { name: "Scarlet Witch" },
  { name: "Scarlet Witch (Age of Apocalypse)" },
  { name: "Scarlet Witch (Marvel Heroes)" },
  { name: "Scarlet Witch (Ultimate)" },
  { name: "Scorpion (Carmilla Black)" },
  { name: "Scorpion (Ultimate)" },
  { name: "Scourge" },
  { name: "Scrambler" },
  { name: "Scream (Donna Diego)" },
  { name: "Screwball" },
  { name: "Sebastian Shaw" },
  { name: "Secret Warriors" },
  { name: "Selene" },
  { name: "Senator Kelly" },
  { name: "Sentinel" },
  { name: "Sentinels" },
  { name: "Sentry (Robert Reynolds)" },
  { name: "Ser Duncan" },
  { name: "Serpent Society" },
  { name: "Sersi" },
  { name: "Shadow King" },
  { name: "Shadow King (Age of Apocalypse)" },
  { name: "Shadowcat" },
  { name: "Shadowcat (Age of Apocalypse)" },
  { name: "Shadowcat (Ultimate)" },
  { name: "Shadu the Shady" },
  { name: "Shalla-bal" },
  { name: "Shaman" },
  { name: "Shane Yamada-Jones" },
  { name: "Shang-Chi" },
  { name: "Shang-Chi (Ultimate)" },
  { name: "Shanna the She-Devil" },
  { name: "Shape" },
  { name: "Shard" },
  { name: "Sharon Carter" },
  { name: "Sharon Ventura" },
  { name: "Shatterstar" },
  { name: "She-Hulk (HAS)" },
  { name: "She-Hulk (Jennifer Walters)" },
  { name: "She-Hulk (Lyra)" },
  { name: "She-Hulk (Marvel War of Heroes)" },
  { name: "She-Hulk (Ultimate)" },
  { name: "Shen" },
  { name: "Sheva Callister" },
  { name: "Shi'Ar" },
  { name: "Shinko Yamashiro" },
  { name: "Shinobi Shaw" },
  { name: "Shiva" },
  { name: "Shiver Man" },
  { name: "Shocker (Herman Schultz)" },
  { name: "Shockwave" },
  { name: "Shooting Star" },
  { name: "Shotgun" },
  { name: "Shriek" },
  { name: "Sif" },
  { name: "Silhouette" },
  { name: "Silk Fever" },
  { name: "Silver Centurion" },
  { name: "Silver Fox" },
  { name: "Silver Sable" },
  { name: "Silver Samurai" },
  { name: "Silver Samurai (Age of Apocalypse)" },
  { name: "Silver Surfer" },
  { name: "Silverclaw" },
  { name: "Silvermane" },
  { name: "Sin" },
  { name: "Sinister Six" },
  { name: "Sir Ram" },
  { name: "Siren (Earth-93060)" },
  { name: "Sister Grimm" },
  { name: "Skaar" },
  { name: "Skaar (HAS)" },
  { name: "Skin" },
  { name: "Skreet" },
  { name: "Skrulls" },
  { name: "Skrulls (Ultimate)" },
  { name: "Skullbuster (Cylla Markham)" },
  { name: "Slapstick" },
  { name: "Slayback" },
  { name: "Sleeper" },
  { name: "Sleepwalker" },
  { name: "Slipstream" },
  { name: "Slyde" },
  { name: "Smasher (Vril Rokk)" },
  { name: "Smiling Tiger" },
  { name: "Snowbird" },
  { name: "Solo (James Bourne)" },
  { name: "Songbird" },
  { name: "Sons of the Tiger" },
  { name: "Spacker Dave" },
  { name: "Spectrum" },
  { name: "Speed" },
  { name: "Speed Demon" },
  { name: "Speedball (Robert Baldwin)" },
  { name: "Spencer Smythe" },
  { name: "Sphinx (Anath-Na Mut)" },
  { name: "Spider-dok" },
  { name: "Spider-Girl (Anya Corazon)" },
  { name: "Spider-Girl (May Parker)" },
  { name: "Spider-Ham (Larval Earth)" },
  { name: "Spider-Man" },
  { name: "Spider-Man (1602)" },
  { name: "Spider-Man (2099)" },
  { name: "Spider-Man (Ai Apaec)" },
  { name: "Spider-Man (Ben Reilly)" },
  { name: "Spider-Man (House of M)" },
  { name: "Spider-Man (LEGO Marvel Super Heroes)" },
  { name: "Spider-Man (Marvel Zombies)" },
  { name: "Spider-Man (Marvel: Avengers Alliance)" },
  { name: "Spider-Man (Miles Morales)" },
  { name: "Spider-Man (Noir)" },
  { name: "Spider-Man (Takuya Yamashiro)" },
  { name: "Spider-Man (Ultimate)" },
  { name: "Spider-Woman (Charlotte Witter)" },
  { name: "Spider-Woman (Jessica Drew)" },
  { name: "Spider-Woman (Mattie Franklin)" },
  { name: "Spiral (Rita Wayword)" },
  { name: "Spirit" },
  { name: "Spitfire" },
  { name: "Spot" },
  { name: "Sprite" },
  { name: "Spyke" },
  { name: "Squadron Sinister" },
  { name: "Squadron Supreme (Earth-712)" },
  { name: "Squirrel Girl" },
  { name: "Stacy X" },
  { name: "Stacy X (Ultimate)" },
  { name: "Star Brand" },
  { name: "Star-Lord (Peter Quill)" },
  { name: "Starbolt" },
  { name: "Stardust" },
  { name: "Starfox" },
  { name: "Starhawk (Stakar Ogord)" },
  { name: "Starjammers" },
  { name: "Stark Industries" },
  { name: "Stature" },
  { name: "Steel Serpent (Davos)" },
  { name: "Stellaris" },
  { name: "Stepford Cuckoos" },
  { name: "Stephanie de la Spiroza" },
  { name: "Stephen Strange" },
  { name: "Steve Rogers" },
  { name: "Stick" },
  { name: "Stilt-Man (Wibur Day)" },
  { name: "Stingray (Walter Newell)" },
  { name: "Stone Men" },
  { name: "Storm" },
  { name: "Storm (Age of Apocalypse)" },
  { name: "Storm (Marvel Heroes)" },
  { name: "Storm (Ultimate)" },
  { name: "Stranger" },
  { name: "Strong Guy" },
  { name: "Stryfe" },
  { name: "Stryfe (Ultimate)" },
  { name: "Sub-Mariner" },
  { name: "Sue Storm" },
  { name: "Sugar Man" },
  { name: "Sumo" },
  { name: "Sunfire" },
  { name: "Sunfire (Age of Apocalypse)" },
  { name: "Sunset Bain" },
  { name: "Sunspot" },
  { name: "Super Hero Squad" },
  { name: "Super-Adaptoid" },
  { name: "Super-Skrull" },
  { name: "Supernaut" },
  { name: "Supreme Intelligence" },
  { name: "Surge" },
  { name: "Susan Delgado" },
  { name: "Swarm" },
  { name: "Sway" },
  { name: "Switch" },
  { name: "Swordsman" },
  { name: "Swordsman (Jaques Duquesne)" },
  { name: "Sym" },
  { name: "Synch" },
  { name: "T'Challa" },
  { name: "Tag" },
  { name: "Talisman (Elizabeth Twoyoungmen)" },
  { name: "Talkback (Chase Stein)" },
  { name: "Talon (Fraternity of Raptors)" },
  { name: "Talos" },
  { name: "Tana Nile" },
  { name: "Tarantula (Luis Alvarez)" },
  { name: "Tarot" },
  { name: "Taskmaster" },
  { name: "Tattoo" },
  { name: "Ted Forrester" },
  { name: "Tempest" },
  { name: "Tenebrous" },
  { name: "Terrax" },
  { name: "Terror" },
  { name: "Texas Twister" },
  { name: "Thaddeus Ross" },
  { name: "Thanos" },
  { name: "Thanos (Ultimate)" },
  { name: "The 198" },
  { name: "The Anarchist" },
  { name: "The Call" },
  { name: "The Captain" },
  { name: "The Enforcers" },
  { name: "The Executioner" },
  { name: "The Fallen" },
  { name: "The Fury" },
  { name: "The Hand" },
  { name: "The Hood" },
  { name: "The Howling Commandos" },
  { name: "The Hunter" },
  { name: "The Initiative" },
  { name: "The Leader (HAS)" },
  { name: "The Liberteens" },
  { name: "The Liberty Legion" },
  { name: "The Order" },
  { name: "The Phantom" },
  { name: "The Professor" },
  { name: "The Renegades" },
  { name: "The Santerians" },
  { name: "The Shiver Man" },
  { name: "The Spike" },
  { name: "The Stranger" },
  { name: "The Twelve" },
  { name: "The Watchers" },
  { name: "Thena" },
  { name: "Thing" },
  { name: "Thing (Marvel Heroes)" },
  { name: "Thing (Ultimate)" },
  { name: "Thor" },
  { name: "Thor (Goddess of Thunder)" },
  { name: "Thor (MAA)" },
  { name: "Thor (Marvel Heroes)" },
  { name: "Thor (Marvel War of Heroes)" },
  { name: "Thor (Marvel: Avengers Alliance)" },
  { name: "Thor (Ultimate)" },
  { name: "Thor Girl" },
  { name: "Thunderball" },
  { name: "Thunderbird (John Proudstar)" },
  { name: "Thunderbird (Neal Shaara)" },
  { name: "Thunderbolt (Bill Carver)" },
  { name: "Thunderbolt Ross" },
  { name: "Thunderbolts" },
  { name: "Thundra" },
  { name: "Tiger Shark" },
  { name: "Tiger's Beautiful Daughter" },
  { name: "Tigra (Greer Nelson)" },
  { name: "Timeslip" },
  { name: "Tinkerer" },
  { name: "Tippy Toe" },
  { name: "Titania" },
  { name: "Titanium Man (Topolov)" },
  { name: "Toad" },
  { name: "Toad Men" },
  { name: "Tomas" },
  { name: "Tombstone" },
  { name: "Tomorrow Man" },
  { name: "Tony Stark" },
  { name: "Toro (Thomas Raymond)" },
  { name: "Toxin" },
  { name: "Toxin (Eddie Brock)" },
  { name: "Trauma" },
  { name: "Triathlon" },
  { name: "Trish Tilby" },
  { name: "Triton" },
  { name: "True Believers" },
  { name: "Turbo" },
  { name: "Tusk" },
  { name: "Two-Gun Kid" },
  { name: "Tyger Tiger" },
  { name: "Typhoid Mary" },
  { name: "Tyrannus" },
  { name: "U-Foes" },
  { name: "U-Go Girl" },
  { name: "U.S. Agent" },
  { name: "Uatu The Watcher" },
  { name: "Ulik" },
  { name: "Ultimate Spider-Man (USM)" },
  { name: "Ultimates" },
  { name: "Ultimatum" },
  { name: "Ultimo" },
  { name: "Ultra-Adaptoid" },
  { name: "Ultragirl (Earth-93060)" },
  { name: "Ultron" },
  { name: "Umar" },
  { name: "Unicorn" },
  { name: "Union Jack (Brian Falsworth)" },
  { name: "Union Jack (Joseph Chapman)" },
  { name: "Union Jack (Montgomery Falsworth)" },
  { name: "Unus" },
  { name: "Unus (Age of Apocalypse)" },
  { name: "Unus (House of M)" },
  { name: "Unus (Ultimate)" },
  { name: "Valeria Richards" },
  { name: "Valkyrie (Samantha Parrington)" },
  { name: "Valkyrie (Ultimate)" },
  { name: "Vampiro" },
  { name: "Vance Astro" },
  { name: "Vanisher (Age of Apocalypse)" },
  { name: "Vanisher (Telford Porter)" },
  { name: "Vanisher (Ultimate)" },
  { name: "Vapor" },
  { name: "Vargas" },
  { name: "Vector" },
  { name: "Veda" },
  { name: "Vengeance (Michael Badilino)" },
  { name: "Venom (Flash Thompson)" },
  { name: "Venom (Mac Gargan)" },
  { name: "Venom (Ultimate)" },
  { name: "Venus (Siren)" },
  { name: "Venus Dee Milo" },
  { name: "Vermin (Edward Whelan)" },
  { name: "Vertigo (Savage Land Mutate)" },
  { name: "Victor Mancha" },
  { name: "Victor Von Doom" },
  { name: "Vin Gonzales" },
  { name: "Vindicator" },
  { name: "Violations" },
  { name: "Viper" },
  { name: "Virginia Dare" },
  { name: "Vision" },
  { name: "Vivisector" },
  { name: "Vulcan (Gabriel Summers)" },
  { name: "Vulture (Adrian Toomes)" },
  { name: "Vulture (Blackie Drago)" },
  { name: "Wallflower" },
  { name: "Wallop" },
  { name: "Wallow" },
  { name: "War (Abraham Kieros)" },
  { name: "War Machine (Iron Man 3 - The Official Game)" },
  { name: "War Machine (Marvel: Avengers Alliance)" },
  { name: "War Machine (Parnell Jacobs)" },
  { name: "War Machine (Ultimate)" },
  { name: "Warbird" },
  { name: "Warbound" },
  { name: "Warhawk (Mitchell Tanner)" },
  { name: "Warlock (Janie Chin)" },
  { name: "Warlock (Technarchy)" },
  { name: "Warpath" },
  { name: "Warren Worthington III" },
  { name: "Warstar" },
  { name: "Wasp" },
  { name: "Wasp (Ultimate)" },
  { name: "Weapon Omega" },
  { name: "Weapon X" },
  { name: "Wendell Rand" },
  { name: "Wendell Vaughn" },
  { name: "Wendigo" },
  { name: "Werewolf By Night" },
  { name: "Whiplash (Mark Scarlotti)" },
  { name: "Whirlwind" },
  { name: "Whistler" },
  { name: "White Queen (Adrienne Frost)" },
  { name: "White Tiger (Angela Del Toro)" },
  { name: "White Tiger (USM)" },
  { name: "Whizzer (Stanley Stewart)" },
  { name: "Wiccan" },
  { name: "Wild Child" },
  { name: "Wild Child (Age of Apocalypse)" },
  { name: "Wild Pack" },
  { name: "Wildside" },
  { name: "William Stryker" },
  { name: "Wilson Fisk" },
  { name: "Wind Dancer" },
  { name: "Winter Soldier" },
  { name: "Wither" },
  { name: "Wolf Cub" },
  { name: "Wolfpack" },
  { name: "Wolfsbane" },
  { name: "Wolfsbane (Age of Apocalypse)" },
  { name: "Wolver-dok" },
  { name: "Wolverine" },
  { name: "Wolverine (LEGO Marvel Super Heroes)" },
  { name: "Wolverine (Marvel War of Heroes)" },
  { name: "Wolverine (Ultimate)" },
  { name: "Wolverine (X-Men: Battle of the Atom)" },
  { name: "Wonder Man" },
  { name: "Wong" },
  { name: "Wong (Ultimate)" },
  { name: "Wraith" },
  { name: "Wrecker" },
  { name: "Wrecking Crew" },
  { name: "X-23" },
  { name: "X-51" },
  { name: "X-Babies" },
  { name: "X-Cutioner" },
  { name: "X-Factor" },
  { name: "X-Factor Investigations" },
  { name: "X-Force" },
  { name: "X-Man" },
  { name: "X-Men" },
  { name: "X-Men (Ultimate)" },
  { name: "X-Ray (James Darnell)" },
  { name: "X-Statix" },
  { name: "X.S.E." },
  { name: "Xavin" },
  { name: "Xorn (Kuan-Yin Xorn)" },
  { name: "Yellow Claw" },
  { name: "Yellowjacket (Rita DeMara)" },
  { name: "Young Avengers" },
  { name: "Young X-Men" },
  { name: "Zaladane" },
  { name: "Zaran" },
  { name: "Zarda" },
  { name: "Zarek" },
  { name: "Zeigeist" },
  { name: "Zemo" },
  { name: "Zodiak" },
  { name: "Zombie (Simon Garth)" },
  { name: "Zuras" },
  { name: "Zzzax" },
];
