import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Button from "@mui/material/Button";
import { styled } from "@mui/material/styles";

const CustomButton = styled(Button)`
  background: red;
  &:hover {
    background: pink;
  }
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <Button variant="contained">Hellow</Button>
          <CustomButton variant="contained">Hello</CustomButton>
        </div>
      </main>
    </>
  );
}
